// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getInitialState: () => typedError<InitialState, string>(__TAURI_INVOKE("get_initial_state")),
	saveSettings: (endpoint: string, model: string, apiKey: string, systemPrompt: string) => typedError<string, string>(__TAURI_INVOKE("save_settings", { endpoint, model, apiKey, systemPrompt })),
	sendMessage: (draft: string, endpoint: string, model: string, apiKey: string, systemPrompt: string) => typedError<string, string>(__TAURI_INVOKE("send_message", { draft, endpoint, model, apiKey, systemPrompt })),
	/**
	 *  Records the operator's approve/reject decision for one pending mutation
	 *  tool call (see issue #208's follow-up). Once every pending id from the
	 *  same round has a resolution, resumes the suspended tool-calling loop —
	 *  dispatching approved calls via the same `chat_tools::dispatch_mcp_tool`
	 *  path as any other tool call, and synthesizing a declined-tool-result for
	 *  rejected ones — and emits the same `chat-update` event `send_message`
	 *  does. Until every pending id is resolved, only records the decision and
	 *  returns a short status string; nothing is dispatched early.
	 */
	confirmPendingToolCall: (callId: string, approved: boolean) => typedError<string, string>(__TAURI_INVOKE("confirm_pending_tool_call", { callId, approved })),
	loadRhaiRulePrompt: (currentModel: string, currentSystemPrompt: string) => typedError<RhaiPromptPayload, string>(__TAURI_INVOKE("load_rhai_rule_prompt", { currentModel, currentSystemPrompt })),
	useInternalPhi: (systemPrompt: string) => typedError<ChatSettingsPayload, string>(__TAURI_INVOKE("use_internal_phi", { systemPrompt })),
	useFoundryLocal: (systemPrompt: string) => typedError<ChatSettingsPayload, string>(__TAURI_INVOKE("use_foundry_local", { systemPrompt })),
	useCloudModel: (systemPrompt: string) => typedError<ChatSettingsPayload, string>(__TAURI_INVOKE("use_cloud_model", { systemPrompt })),
	openDocsPlaybook: () => typedError<string, string>(__TAURI_INVOKE("open_docs_playbook")),
	getEvidenceDashboard: () => typedError<EvidenceDashboardPayload, string>(__TAURI_INVOKE("get_evidence_dashboard")),
	getTxProvenance: (txId: string) => typedError<ProvenancePayload, string>(__TAURI_INVOKE("get_tx_provenance", { txId })),
	getTestHarnessConfig: () => __TAURI_INVOKE<TestHarnessConfig>("get_test_harness_config"),
	writeDomDump: (dump: string) => __TAURI_INVOKE<string>("write_dom_dump", { dump }),
	getCargoPkgVersion: () => __TAURI_INVOKE<string>("get_cargo_pkg_version"),
	/**
	 *  Return the Cytoscape.js-compatible graph for the holonic pipeline.
	 * 
	 *  The frontend Viz panel calls this once on activation. The graph crosses the
	 *  webview boundary as JSON so the model-first visualization types do not gain
	 *  a Rust-first `specta` dependency.
	 */
	getHolonVizGraph: () => typedError<string, string>(__TAURI_INVOKE("get_holon_viz_graph")),
	/**
	 *  Return the Rust type relationship graph for the Viz panel.
	 * 
	 *  Delegates to [`TypeRelationshipGraph::seed()`] in `holon-viz`.
	 */
	getTypeGraph: () => typedError<string, string>(__TAURI_INVOKE("get_type_graph")),
	/**
	 *  Return the controller status as JSON so the webview and Claude MCPB read
	 *  one shared desktop/runtime contract without duplicating probes in JS.
	 */
	getDesktopStatus: () => typedError<string, string>(__TAURI_INVOKE("get_desktop_status")),
	startDesktopRuntime: () => typedError<string, string>(__TAURI_INVOKE("start_desktop_runtime")),
	stopDesktopRuntime: () => typedError<string, string>(__TAURI_INVOKE("stop_desktop_runtime")),
	/**
	 *  Opens only the per-user runtime log directory; no controller action can
	 *  browse or alter arbitrary host paths.
	 */
	openDesktopLogs: () => typedError<string, string>(__TAURI_INVOKE("open_desktop_logs")),
	/**
	 *  UI repair remains plan-only. The user must approve the matching controller
	 *  operation in Claude, preserving the MCPB/UAC boundary.
	 */
	getDesktopRepairPlan: () => typedError<string, string>(__TAURI_INVOKE("get_desktop_repair_plan")),
	getFoundryLocalInstallPlan: () => typedError<string, string>(__TAURI_INVOKE("get_foundry_local_install_plan")),
	foundryLocalInstallAction: (approved: boolean) => typedError<string, string>(__TAURI_INVOKE("foundry_local_install_action", { approved })),
};

/* Types */
export type ChatSettingsPayload = {
	endpoint_text: string,
	model_text: string,
	api_key_text: string,
	system_prompt_text: string,
	status_text: string,
};

export type EvidenceDashboardPayload = {
	today_queue: TodayQueue,
};

export type InitialState = {
	version_text: string,
	status_text: string,
	endpoint_text: string,
	model_text: string,
	api_key_text: string,
	system_prompt_text: string,
	transcript_text: string,
	review_log_text: string,
	rig_log_text: string,
	draft_message_text: string,
	docs_status_text: string,
};

/**
 *  Operator-facing model provider label.
 * 
 *  This label is shown in the host UI instead of the technical backend name.
 *  Each label maps to a readiness state and a setup path.
 */
export type ModelProviderLabel = 
/**  Private local inference. Works immediately. May use a deterministic stub if no GGUF is configured. */
"local_demo" | 
/**  Private local inference via Windows AI / Foundry Local. Requires setup first. */
"windows_ai" | 
/**  Explicit external API call. Requires operator-supplied endpoint and key. */
"cloud";

export type ProvenancePayload = {
	badge: string,
	css_class: string,
};

/**
 *  Combined provider info for the host UI.
 * 
 *  Returned by `provider_status()` to populate the model-mode selector.
 */
export type ProviderInfo = {
	label: ModelProviderLabel,
	display_name: string,
	description: string,
	readiness: ProviderReadiness,
	is_default: boolean,
};

/**  Readiness state for a model provider. */
export type ProviderReadiness = 
/**  Provider can send requests now. */
"ready" | 
/**  Provider needs one setup step before use. */
({ setup_needed: {
	next_command: string,
} }) & { diagnostic?: never; unavailable?: never } | 
/**  Provider cannot be used in the current environment. */
({ unavailable: {
	reason: string,
} }) & { diagnostic?: never; setup_needed?: never } | 
/**  Provider endpoint exists but a smoke test or model load failed. */
({ diagnostic: {
	reason: string,
} }) & { setup_needed?: never; unavailable?: never };

export type RhaiPromptPayload = {
	system_prompt: string,
	/**  Non-empty when the caller should switch to this model (e.g. DEFAULT_RHAI_RULE_MODEL) */
	suggested_model: string,
	draft_message: string,
	review_log_text: string,
	status: string,
};

export type TestHarnessConfig = {
	kill_delay_ms: number,
	screenshot_path: string,
	pkg_version: string,
	build_number: string,
};

export type TodayQueue = {
	providers: ProviderInfo[],
	ready_to_review: number,
	blocked: number,
	exported: number,
	/**  Transactions that have ValidationIssue nodes attached. */
	with_validation_issues: number,
	last_action_summary: string,
	next_actions: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

