// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getInitialState: () => typedError<InitialState, string>(__TAURI_INVOKE("get_initial_state")),
	saveSettings: (endpoint: string, model: string, apiKey: string, systemPrompt: string) => typedError<string, string>(__TAURI_INVOKE("save_settings", { endpoint, model, apiKey, systemPrompt })),
	sendMessage: (draft: string, endpoint: string, model: string, apiKey: string, systemPrompt: string) => typedError<string, string>(__TAURI_INVOKE("send_message", { draft, endpoint, model, apiKey, systemPrompt })),
	loadRhaiRulePrompt: (currentModel: string, currentSystemPrompt: string) => typedError<RhaiPromptPayload, string>(__TAURI_INVOKE("load_rhai_rule_prompt", { currentModel, currentSystemPrompt })),
	useInternalPhi: (systemPrompt: string) => typedError<ChatSettingsPayload, string>(__TAURI_INVOKE("use_internal_phi", { systemPrompt })),
	useFoundryLocal: (systemPrompt: string) => typedError<ChatSettingsPayload, string>(__TAURI_INVOKE("use_foundry_local", { systemPrompt })),
	useCloudModel: (systemPrompt: string) => typedError<ChatSettingsPayload, string>(__TAURI_INVOKE("use_cloud_model", { systemPrompt })),
	openDocsPlaybook: () => typedError<string, string>(__TAURI_INVOKE("open_docs_playbook")),
	getEvidenceDashboard: () => typedError<EvidenceDashboardPayload, string>(__TAURI_INVOKE("get_evidence_dashboard")),
	getTxProvenance: (txId: string) => typedError<ProvenancePayload, string>(__TAURI_INVOKE("get_tx_provenance", { txId })),
	getTestHarnessConfig: () => __TAURI_INVOKE<TestHarnessConfig>("get_test_harness_config"),
	writeDomDump: (dump: string) => __TAURI_INVOKE<string>("write_dom_dump", { dump }),
	getCargoPkgVersion: () => __TAURI_INVOKE<string>("get_cargo_pkg_version"),
	/**
	 *  Return the Cytoscape.js-compatible graph for the holonic pipeline.
	 * 
	 *  The frontend Viz panel calls this once on activation. `tauri-specta` generates
	 *  typed TypeScript bindings from the `CytoscapeGraph` return type.
	 */
	getHolonVizGraph: () => typedError<CytoscapeGraph_Serialize, string>(__TAURI_INVOKE("get_holon_viz_graph")),
	/**
	 *  Return the Rust type relationship graph for the Viz panel.
	 * 
	 *  Delegates to [`TypeRelationshipGraph::seed()`] in `holon-viz`.
	 */
	getTypeGraph: () => typedError<CytoscapeGraph_Serialize, string>(__TAURI_INVOKE("get_type_graph")),
};

/* Types */
export type ChatSettingsPayload = {
	endpoint_text: string,
	model_text: string,
	api_key_text: string,
	system_prompt_text: string,
	status_text: string,
};

/**  A single Cytoscape.js edge element. */
export type CytoscapeEdge = {
	data: CytoscapeEdgeData,
};

/**  Data payload for a Cytoscape.js edge element. */
export type CytoscapeEdgeData = {
	id: string,
	source: string,
	target: string,
	label: string,
};

/**
 *  Serializable Cytoscape.js graph — nodes and edges with `data` fields.
 * 
 *  Construct via [`HolonGraph::from_holons`].
 */
export type CytoscapeGraph = CytoscapeGraph_Serialize | CytoscapeGraph_Deserialize;

/**
 *  Serializable Cytoscape.js graph — nodes and edges with `data` fields.
 * 
 *  Construct via [`HolonGraph::from_holons`].
 */
export type CytoscapeGraph_Deserialize = {
	nodes: CytoscapeNode_Deserialize[],
	edges: CytoscapeEdge[],
};

/**
 *  Serializable Cytoscape.js graph — nodes and edges with `data` fields.
 * 
 *  Construct via [`HolonGraph::from_holons`].
 */
export type CytoscapeGraph_Serialize = {
	nodes: CytoscapeNode_Serialize[],
	edges: CytoscapeEdge[],
};

/**  A single Cytoscape.js node element. */
export type CytoscapeNode = CytoscapeNode_Serialize | CytoscapeNode_Deserialize;

/**  Data payload for a Cytoscape.js node element. */
export type CytoscapeNodeData = CytoscapeNodeData_Serialize | CytoscapeNodeData_Deserialize;

/**  Data payload for a Cytoscape.js node element. */
export type CytoscapeNodeData_Deserialize = {
	id: string,
	label: string,
	kind: string,
	/**  Optional parent for compound graphs (Cytoscape compound nodes). */
	parent: string | null,
	/**  `ZLayer` variant from `HasVisualization::viz_spec()`, if available. */
	z_layer: string | null,
	/**  `SemanticType` variant from `HasVisualization::viz_spec()`, if available. */
	semantic_type: string | null,
};

/**  Data payload for a Cytoscape.js node element. */
export type CytoscapeNodeData_Serialize = {
	id: string,
	label: string,
	kind: string,
	/**  Optional parent for compound graphs (Cytoscape compound nodes). */
	parent?: string | null,
	/**  `ZLayer` variant from `HasVisualization::viz_spec()`, if available. */
	z_layer?: string | null,
	/**  `SemanticType` variant from `HasVisualization::viz_spec()`, if available. */
	semantic_type?: string | null,
};

/**  A single Cytoscape.js node element. */
export type CytoscapeNode_Deserialize = {
	data: CytoscapeNodeData_Deserialize,
};

/**  A single Cytoscape.js node element. */
export type CytoscapeNode_Serialize = {
	data: CytoscapeNodeData_Serialize,
};

export type EvidenceDashboardPayload = {
	today_queue: TodayQueue,
};

export type InitialState = {
	version_text: string,
	status_text: string,
	endpoint_text: string,
	model_text: string,
	api_key_text: string,
	system_prompt_text: string,
	transcript_text: string,
	review_log_text: string,
	rig_log_text: string,
	draft_message_text: string,
	docs_status_text: string,
};

/**
 *  Operator-facing model provider label.
 * 
 *  This label is shown in the host UI instead of the technical backend name.
 *  Each label maps to a readiness state and a setup path.
 */
export type ModelProviderLabel = 
/**  Private local inference. Works immediately. May use a deterministic stub if no GGUF is configured. */
"local_demo" | 
/**  Private local inference via Windows AI / Foundry Local. Requires setup first. */
"windows_ai" | 
/**  Explicit external API call. Requires operator-supplied endpoint and key. */
"cloud";

export type ProvenancePayload = {
	badge: string,
	css_class: string,
};

/**
 *  Combined provider info for the host UI.
 * 
 *  Returned by `provider_status()` to populate the model-mode selector.
 */
export type ProviderInfo = {
	label: ModelProviderLabel,
	display_name: string,
	description: string,
	readiness: ProviderReadiness,
	is_default: boolean,
};

/**  Readiness state for a model provider. */
export type ProviderReadiness = 
/**  Provider can send requests now. */
"ready" | 
/**  Provider needs one setup step before use. */
({ setup_needed: {
	next_command: string,
} }) & { diagnostic?: never; unavailable?: never } | 
/**  Provider cannot be used in the current environment. */
({ unavailable: {
	reason: string,
} }) & { diagnostic?: never; setup_needed?: never } | 
/**  Provider endpoint exists but a smoke test or model load failed. */
({ diagnostic: {
	reason: string,
} }) & { setup_needed?: never; unavailable?: never };

export type RhaiPromptPayload = {
	system_prompt: string,
	/**  Non-empty when the caller should switch to this model (e.g. DEFAULT_RHAI_RULE_MODEL) */
	suggested_model: string,
	draft_message: string,
	review_log_text: string,
	status: string,
};

export type TestHarnessConfig = {
	kill_delay_ms: number,
	screenshot_path: string,
	pkg_version: string,
	build_number: string,
};

export type TodayQueue = {
	providers: ProviderInfo[],
	ready_to_review: number,
	blocked: number,
	exported: number,
	/**  Transactions that have ValidationIssue nodes attached. */
	with_validation_issues: number,
	last_action_summary: string,
	next_actions: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

