//! E2E Visualization Tests
//! Tests the pipeline flow visualization (Mermaid/HTML) generated by `ledger-core::visualize`.

use ledger_core::pipeline::State as PipelineState;
use ledger_core::validation::{Issue, IssueSource};
use ledger_core::visualize::{
    layout::LayoutSolver, to_html, EdgeVisual, NodeVisualState, PipelineGraph,
};
use ledger_core::workflow::examples::ledger_ingest;

/// Test: Full pipeline visualization cycle from ingest to commit.
#[test]
fn test_e2e_pipeline_visualization() {
    // 1. Start with empty graph
    let mut graph = PipelineGraph::new();
    assert_eq!(graph.current_state, "Ingested");
    assert!((graph.accumulated_confidence - 1.0).abs() < 0.001);

    // 2. Initialize from workflow TOML
    let wf = ledger_ingest();
    for state in &wf.state {
        graph.nodes.insert(state.id.clone(), NodeVisualState::Idle);
    }
    for trans in &wf.transitions {
        graph
            .edges
            .push(EdgeVisual::new(&trans.from, &trans.to, &trans.event));
    }

    // 3. Stage 1: Ingested -> Validating
    let mermaid = graph.to_mermaid();
    assert!(mermaid.contains("Ingested"));
    assert!(mermaid.contains("Validating"));
}

/// Test: Visualization with high confidence state.
#[test]
fn test_high_confidence_state() {
    let mut graph = PipelineGraph::new();
    graph
        .nodes
        .insert("Ingested".to_string(), NodeVisualState::Success);
    graph
        .nodes
        .insert("Validating".to_string(), NodeVisualState::Active);
    graph
        .nodes
        .insert("Classifying".to_string(), NodeVisualState::Idle);
    graph.current_state = "Validating".to_string();
    graph.accumulated_confidence = 0.92;

    let html = to_html(&graph);
    assert!(html.contains("stateDiagram-v2"));
    assert!(html.contains("0.92"));
    assert!(html.contains("#4caf50"));
}

/// Test: Visualization with low confidence (warning state).
#[test]
fn test_low_confidence_warning() {
    let mut graph = PipelineGraph::new();
    graph
        .nodes
        .insert("Validating".to_string(), NodeVisualState::Warning);
    graph.current_state = "Validating".to_string();
    graph.accumulated_confidence = 0.35;

    let html = to_html(&graph);
    assert!(html.contains("#ff9800"));
}

/// Test: Error state visualization.
#[test]
fn test_error_state() {
    let mut graph = PipelineGraph::new();
    graph
        .nodes
        .insert("Validating".to_string(), NodeVisualState::Error);
    graph.current_state = "Validating".to_string();
    graph.accumulated_confidence = 0.0;

    let html = to_html(&graph);
    assert!(html.contains("#f44336"));
}

/// Test: Review required state.
#[test]
fn test_review_state() {
    let mut graph = PipelineGraph::new();
    graph
        .nodes
        .insert("NeedsReview".to_string(), NodeVisualState::Review);
    graph.current_state = "NeedsReview".to_string();

    let html = to_html(&graph);
    assert!(html.contains("#9c27b0"));
}

/// Test: Animation styles are generated.
#[test]
fn test_animation_styles() {
    let graph = PipelineGraph::new();
    let styles = graph.animation_styles();

    assert!(styles.contains("@keyframes pulse"));
    assert!(styles.contains("@keyframes check"));
    assert!(styles.contains("@keyframes shake"));
}

/// Test: Layout solver produces positions.
#[test]
fn test_layout_solver() {
    let solver = LayoutSolver::new();
    let mut graph = PipelineGraph::new();
    graph
        .nodes
        .insert("Ingested".to_string(), NodeVisualState::Success);
    graph
        .nodes
        .insert("Validating".to_string(), NodeVisualState::Active);
    graph.current_state = "Validating".to_string();
    graph.accumulated_confidence = 0.8;

    let layout = solver.generate_layout(&graph);

    assert!(layout.contains_key("Ingested"));
    assert!(layout.contains_key("Validating"));

    let (_, active_width) = layout.get("Validating").unwrap();
    let (_, ingest_width) = layout.get("Ingested").unwrap();
    assert!(*active_width > *ingest_width);
}

/// Test: NodeVisualState from pipeline with issues.
#[test]
fn test_node_from_pipeline_with_issues() {
    let issues = vec![Issue::recoverable(
        "test",
        "warning",
        IssueSource::TypeCheck,
    )];

    let state = NodeVisualState::from_pipeline(PipelineState::Validating, 0.3, &issues);
    // Low confidence + recoverable issues = Warning
    assert_eq!(state, NodeVisualState::Warning);
}

/// Test: NodeVisualState from pipeline with unrecoverable.
#[test]
fn test_node_unrecoverable() {
    let issues = vec![Issue::unrecoverable("fatal", "cannot continue")];

    let state = NodeVisualState::from_pipeline(PipelineState::Validating, 0.9, &issues);
    assert_eq!(state, NodeVisualState::Error);
}

/// Test: Complete HTML visualization.
#[test]
fn test_complete_html() {
    let wf = ledger_ingest();
    let mut graph = PipelineGraph::new();

    for state in &wf.state {
        graph.nodes.insert(state.id.clone(), NodeVisualState::Idle);
    }

    graph.current_state = "Classifying".to_string();
    graph.accumulated_confidence = 0.78;
    if let Some(s) = graph.nodes.get_mut("Classifying") {
        *s = NodeVisualState::Active;
    }

    let html = to_html(&graph);

    assert!(html.contains("<!DOCTYPE html>"));
    assert!(html.contains("mermaid"));
    assert!(html.contains("@keyframes"));
    // Confidence is formatted as percentage
    assert!(html.contains("0.78") || html.contains("78") || html.contains("0.8"));
}

/// Integration test: workflow to visualization roundtrip.
#[test]
fn test_workflow_to_visualization_roundtrip() {
    let wf = ledger_ingest();
    assert!(wf.validate().is_ok());

    let mut graph = PipelineGraph::new();
    for state in &wf.state {
        graph.nodes.insert(state.id.clone(), NodeVisualState::Idle);
    }
    for trans in &wf.transitions {
        graph
            .edges
            .push(EdgeVisual::new(&trans.from, &trans.to, &trans.event));
    }

    let mermaid = graph.to_mermaid();
    assert!(mermaid.contains("stateDiagram-v2"));

    for state in &wf.state {
        assert!(mermaid.contains(&state.id), "Missing state: {}", state.id);
    }

    let solver = LayoutSolver::new();
    let layout = solver.generate_layout(&graph);
    assert!(!layout.is_empty());
}
