[CmdletBinding()]
param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")),
    [ValidateSet("debug", "release")]
    [string]$Configuration = "release",
    [switch]$Package,
    [string]$Version = "0.1.0",
    [string]$OutputDir
)

$ErrorActionPreference = "Stop"
if (-not $OutputDir) { $OutputDir = Join-Path $RepoRoot "dist\\windows" }

Push-Location $RepoRoot
try {
    $cargoArgs = @("build", "-p", "ledgerr-host", "--bin", "host-tauri")
    if ($Configuration -eq "release") { $cargoArgs += "--release" }
    Write-Host "[build] cargo $($cargoArgs -join ' ')"
    & cargo @cargoArgs
    if ($LASTEXITCODE -ne 0) { throw "host-tauri build failed (exit $LASTEXITCODE)" }
} finally {
    Pop-Location
}

$binary = Join-Path $RepoRoot "target\\$Configuration\\host-tauri.exe"
if (-not (Test-Path $binary -PathType Leaf)) { throw "host-tauri binary not found: $binary" }
$hash = (Get-FileHash $binary -Algorithm SHA256).Hash.ToLowerInvariant()
$datumDir = Join-Path $RepoRoot ".b00t\\datums"
New-Item -ItemType Directory -Force -Path $datumDir | Out-Null

@"
# ledgrrr datum -- generated by scripts/tauri-build.ps1
[datum]
name = "host-tauri"
version = "$Version"
kind = "binary"

[build]
cargo_profile = "$Configuration"
package_format = "msix-external-location"

[artifact]
path = "$binary"
sha256 = "$hash"
"@ | Set-Content -Encoding utf8 (Join-Path $datumDir "host-tauri.toml")

Write-Host "Built: $binary"
Write-Host "SHA256: $hash"
if ($Package) {
    & (Join-Path $RepoRoot "scripts\\windows-package.ps1") -Action Build -RepoRoot $RepoRoot -Version $Version -OutputDir $OutputDir
    if ($LASTEXITCODE -ne 0) { throw "Windows MSIX package build failed (exit $LASTEXITCODE)" }
}
